name: Project Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build project
        run: npm run build
        env:
          CI: true

      - name: Create artifact
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: dist/
